### ISSUE TITLE
VTR200/B connection type/wirring

### ISSUE THREAD

**Issue by tvc-dps** [os11k/vtr200b#1]
Hello/Labdien

I see you are using very the same Systemair model VTR200/B that I need to make the installation. I do not have free access to the top of the unit - not easy to identify connectors on the top.

Could you please help:
 - Waveshare RS485 unit connected to VTR200/B modbus port
 - What jack type is used for Modbus port at VTR200/B - rj10 or rj45? (if you share the picture of connection it would help me a lot)
 - Could you please share the wiring schema?

Thank you in advance
Malik

**Comment by os11k** [comment]
Hi,
Waveshare RS485, you can get from eay, something like that one:
https://www.ebay.com/itm/255747041868?_skw=Waveshare+RS485&itmmeta=01J9RM2FWHHT6TDRHR7B4CJ3GJ&hash=item3b8bb62a4c%3Ag%3AW%7EcAAOSwKb9jMr2p&itmprp=enc%3AAQAJAAAA8HoV3kP08IDx%2BKZ9MfhVJKmdqqNoqCEaUioLoYhxLC5CB3JAip5aXYMOw5GZWv612V9kw5E8HEvfFoy%2BXnLTpaO4M6MOC8rc8oFnRFPOIuud1D9Es2dF6m3W5LUs%2By2hbM3Y3sNLDbIlz5TAwKhPAMKK6CxF1GMCAB%2F5USsSoH8TKZFbZdHKxgGCzzNceawhKoFldZj%2BONJ9E4k4Yhork9ThwoATBqjPTdJrJOaFpxnHXZB%2F287JJJMeb40JTBbVVJZVBRmWR%2FBIT7XqvHB9aXQer%2BOxmzRNJtlo6%2F80xiDcXdhl06MI7%2B6m2JPBBVnZmw%3D%3D%7Ctkp%3ABk9SR67-iZTOZA&var=555680671976

It is rj45.

Wiring schema is here:

https://camo.githubusercontent.com/043aa0c0b10ad7f6918f2d3d0c19cd348e2c843b503ed5650dd81e34d1d694df/68747470733a2f2f692e696d6775722e636f6d2f705949493365612e6a706567

On connector side, it is just regular ethernet cable:

https://incentre.net/wp-content/uploads/2024/06/ethcable568b.gif

green - ground, blue - B, blue/white - A

Cheers!

**Comment by os11k** [comment]
Hi! Did you figure it out? Do you still need my assistance or I can close this issue? Cheers!

**Comment by tvc-dps** [comment]
thank you
